<?php

/*
 * This file is part of the lisachenko/kafka-client package.
 *
 * (c) Alexander Lisachenko <lisachenko.it@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Protocol\Kafka\Protocol\Request;

use Protocol\Kafka\Protocol\ApiKeys;
use Protocol\Kafka\Protocol\BinarySchema;

/**
 * ShareGroupHeartbeat, version 1: the membership of a share group of KIP-932 in one request (ApiKey 76, Kafka 4.1)
 *
 * <pre>
 *   ShareGroupHeartbeat Request (Version: 1) => group_id member_id member_epoch rack_id [subscribed_topic_names]
 *     group_id               => COMPACT_STRING
 *     member_id              => COMPACT_STRING             -- generated by the member, never empty
 *     member_epoch           => INT32                      -- 0 join, -1 leave, else the current epoch
 *     rack_id                => COMPACT_NULLABLE_STRING    -- null: not provided, or unchanged
 *     subscribed_topic_names => COMPACT_STRING             -- NULLABLE array; null: unchanged
 * </pre>
 *
 * `ShareGroupHeartbeatRequest.json` @ 4.1.0: *"Version 0 was used for early access of KIP-932 in Apache Kafka 4.0
 * but removed in Apache Kafka 4.1. Version 1 is the initial stable version"* - `validVersions` is `1` alone, so there
 * is no keep-behind class. It is the ConsumerGroupHeartbeat of KIP-848 ({@see ConsumerGroupHeartbeatRequest}) without
 * what a share member does not have: no instance id (share groups have no static members), no rebalance timeout, no
 * regex, no server assignor and no `topic_partitions` - a share member acknowledges **records**, with ShareFetch and
 * ShareAcknowledge, never partitions.
 *
 * The member id is the member's own, as in version 1 of the consumer protocol (KIP-1082), and
 * `GroupCoordinatorService.throwIfShareGroupHeartbeatRequestIsInvalid` @ 4.1.0 refuses an empty one with the 42, and a
 * join (epoch 0) without subscribed topic names with the 42 *"SubscribedTopicNames must be set in first request."*.
 *
 * @see docs/protocol/4.3.md, section "ShareGroupHeartbeat API (key 76, v1)"
 */
class ShareGroupHeartbeatRequest extends AbstractRequest
{
    /**
     * @inheritdoc
     */
    public const int API_KEY = ApiKeys::SHARE_GROUP_HEARTBEAT;

    /**
     * @inheritdoc
     */
    public const int VERSION = 1;

    /**
     * The api is flexible from its first version
     */
    public const int FLEXIBLE_VERSION = 0;

    /**
     * Member epoch of a heartbeat that joins the group
     */
    public const int JOIN_MEMBER_EPOCH = 0;

    /**
     * Member epoch of a heartbeat that leaves the group
     */
    public const int LEAVE_MEMBER_EPOCH = -1;

    /**
     * Topics this member subscribed to, or null when they did not change since the last heartbeat
     *
     * @var list<string>|null
     */
    protected readonly ?array $subscribedTopicNames;

    /**
     * @param string            $groupId              Share group the member belongs to
     * @param string            $memberId             Member id, the uuid the member generated for itself
     * @param int               $memberEpoch          0 to join, -1 to leave, else the epoch of the last answer
     * @param list<string>|null $subscribedTopicNames Subscription, null for "unchanged"; a join has to name one
     * @param string|null       $rackId               `client.rack` of the member, null for "not provided"
     * @param string            $clientId             An identifier of the client
     * @param int               $correlationId        A value the broker passes back unmodified
     */
    public function __construct(
        /**
         * Share group the member belongs to
         */
        protected readonly string $groupId,
        /**
         * Member id of the member
         */
        protected readonly string $memberId,
        /**
         * Epoch of the member
         */
        protected readonly int $memberEpoch,
        ?array $subscribedTopicNames = null,
        /**
         * Rack of the member, null when it has none or when it did not change
         */
        protected readonly ?string $rackId = null,
        string $clientId = '',
        int $correlationId = 0
    ) {
        $this->subscribedTopicNames = $subscribedTopicNames === null ? null : array_values($subscribedTopicNames);

        parent::__construct(self::API_KEY, $clientId, $correlationId);
    }

    /**
     * Builds the heartbeat that joins a share group: the epoch 0 and the subscription
     *
     * @param list<string> $subscribedTopicNames Topics the member subscribes to, which a join has to name
     */
    public static function forJoin(
        string $groupId,
        string $memberId,
        array $subscribedTopicNames,
        ?string $rackId = null,
        string $clientId = '',
        int $correlationId = 0
    ): self {
        return new self($groupId, $memberId, self::JOIN_MEMBER_EPOCH, $subscribedTopicNames, $rackId, $clientId, $correlationId);
    }

    /**
     * Builds the heartbeat of a member in its group: its epoch, and the subscription only when it changed
     *
     * @param list<string>|null $subscribedTopicNames New subscription, null when it did not change
     */
    public static function forHeartbeat(
        string $groupId,
        string $memberId,
        int $memberEpoch,
        ?array $subscribedTopicNames = null,
        string $clientId = '',
        int $correlationId = 0
    ): self {
        return new self($groupId, $memberId, $memberEpoch, $subscribedTopicNames, null, $clientId, $correlationId);
    }

    /**
     * Builds the heartbeat that leaves the group: the epoch -1 and nothing else
     */
    public static function forLeave(string $groupId, string $memberId, string $clientId = '', int $correlationId = 0): self
    {
        return new self($groupId, $memberId, self::LEAVE_MEMBER_EPOCH, null, null, $clientId, $correlationId);
    }

    /**
     * @inheritdoc
     */
    public static function getScheme(): array
    {
        return parent::getScheme() + [
            'groupId'              => BinarySchema::TYPE_STRING,
            'memberId'             => BinarySchema::TYPE_STRING,
            'memberEpoch'          => BinarySchema::TYPE_INT32,
            'rackId'               => BinarySchema::TYPE_NULLABLE_STRING,
            'subscribedTopicNames' => [BinarySchema::TYPE_STRING, BinarySchema::FLAG_NULLABLE => true],
        ];
    }

    /**
     * Returns the group this heartbeat belongs to
     */
    public function getGroupId(): string
    {
        return $this->groupId;
    }

    /**
     * Returns the member id this heartbeat names
     */
    public function getMemberId(): string
    {
        return $this->memberId;
    }

    /**
     * Returns the member epoch this heartbeat carries
     */
    public function getMemberEpoch(): int
    {
        return $this->memberEpoch;
    }

    /**
     * Returns the subscription this heartbeat names, null when it did not change
     *
     * @return list<string>|null
     */
    public function getSubscribedTopicNames(): ?array
    {
        return $this->subscribedTopicNames;
    }
}
