<?php

/*
 * This file is part of the lisachenko/kafka-client package.
 *
 * (c) Alexander Lisachenko <lisachenko.it@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Protocol\Kafka\Admin;

use Protocol\Kafka\Protocol\Data\LeaveGroupRequestMember;

/**
 * One member that {@see AdminClient::removeMembersFromConsumerGroup()} removes from its group (KIP-345, Kafka 2.4)
 *
 * A member can be named in two ways, and the coordinator resolves them in this order:
 *
 * * by its **`group.instance.id`** ({@see self::byInstanceId()}), which is what an administrator knows about a
 *   *static* member: it is the name the member was configured with, where its member id was generated by the
 *   coordinator and changes with every restart. This is the `MemberToRemove` of the Java admin client, which takes
 *   nothing else;
 * * by its **member id** ({@see self::byMemberId()}), the way a member removes itself - and the only way to name a
 *   *dynamic* member, which has no instance id at all.
 *
 * {@see self::byBoth()} names both, which makes the coordinator check that the member id really belongs to that
 * instance and answer **82** (`FencedInstanceId`) when another consumer has taken the instance over.
 *
 * @see docs/protocol/2.8.md, section "The batch leave of KIP-345 (v3)"
 */
final class MemberToRemove
{
    /**
     * @param string      $memberId        Member id of the member, empty when the instance id names it
     * @param string|null $groupInstanceId `group.instance.id` of the member, null when the member id names it
     */
    public function __construct(
        public readonly string $memberId = LeaveGroupRequestMember::UNKNOWN_MEMBER_ID,
        public readonly ?string $groupInstanceId = null
    ) {}

    /**
     * Names a static member by its `group.instance.id`, whatever member id it holds right now
     */
    public static function byInstanceId(string $groupInstanceId): self
    {
        return new self(LeaveGroupRequestMember::UNKNOWN_MEMBER_ID, $groupInstanceId);
    }

    /**
     * Names a member by the member id the coordinator assigned to it
     */
    public static function byMemberId(string $memberId): self
    {
        return new self($memberId);
    }

    /**
     * Names a static member by both, so that the coordinator refuses a member id that lost the instance
     */
    public static function byBoth(string $memberId, string $groupInstanceId): self
    {
        return new self($memberId, $groupInstanceId);
    }

    /**
     * Returns how this member is keyed in the result of a removal: its instance id, or its member id
     */
    public function identity(): string
    {
        return $this->groupInstanceId ?? $this->memberId;
    }

    /**
     * Returns the wire entry of this member
     */
    public function toRequestMember(): LeaveGroupRequestMember
    {
        return new LeaveGroupRequestMember($this->memberId, $this->groupInstanceId);
    }
}
